// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRYBEqxVAw3p9QW12gLhfDwtIXB3XXhk',
    appId: '1:368443753050:web:6b586c3c784ce59d68ce63',
    messagingSenderId: '368443753050',
    projectId: 'flutter-sithum-45gb',
    authDomain: 'flutter-sithum-45gb.firebaseapp.com',
    storageBucket: 'flutter-sithum-45gb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABr09BLVXYE6tCqOPkWPSRqOmn5IAovV4',
    appId: '1:368443753050:android:30cbb4745b5d52f468ce63',
    messagingSenderId: '368443753050',
    projectId: 'flutter-sithum-45gb',
    storageBucket: 'flutter-sithum-45gb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCGngqfGvmuyPYm-fBFAnbR2burrNUKg',
    appId: '1:368443753050:ios:a4f464f9d79452d268ce63',
    messagingSenderId: '368443753050',
    projectId: 'flutter-sithum-45gb',
    storageBucket: 'flutter-sithum-45gb.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCGngqfGvmuyPYm-fBFAnbR2burrNUKg',
    appId: '1:368443753050:ios:a4f464f9d79452d268ce63',
    messagingSenderId: '368443753050',
    projectId: 'flutter-sithum-45gb',
    storageBucket: 'flutter-sithum-45gb.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhRYBEqxVAw3p9QW12gLhfDwtIXB3XXhk',
    appId: '1:368443753050:web:0bb858af23d9e95d68ce63',
    messagingSenderId: '368443753050',
    projectId: 'flutter-sithum-45gb',
    authDomain: 'flutter-sithum-45gb.firebaseapp.com',
    storageBucket: 'flutter-sithum-45gb.firebasestorage.app',
  );
}
